# Generated by Django 5.1.3 on 2025-01-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('qtext', models.CharField(default='null', max_length=50)),
                ('answer', models.CharField(default='null', max_length=50)),
                ('op1', models.CharField(default='null', max_length=50)),
                ('op2', models.CharField(default='null', max_length=50)),
                ('op3', models.CharField(default='null', max_length=50)),
                ('op4', models.CharField(default='null', max_length=50)),
                ('subject', models.CharField(default='null', max_length=50)),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('mobno', models.IntegerField(max_length=10)),
                ('emailid', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
